apiVersion: apps/v1
kind: Deployment
metadata:
  name: champ-user-inquiry
  labels:
    app.kubernetes.io/name: champ-user-inquiry
    app.kubernetes.io/instance: champ-user-inquiry
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: champ-user-inquiry
      app.kubernetes.io/instance: champ-user-inquiry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: champ-user-inquiry
        app.kubernetes.io/instance: champ-user-inquiry
    spec:
      containers:
        - name: champ-user-inquiry
          image: asia.gcr.io/poc-innovation-iot/champ-user-inquiry:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: champ-user-inquiry-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: champ-user-inquiry-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: champ-user-inquiry-configmap-file
          configMap:
            name: champ-user-inquiry-configmap-file